"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my honor, Sidarth Vijaya, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: snv453
UT EID 2:
"""


# TODO: implement this function. You may delete this comment when you are done.
def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    a = len(s)
    lng = 0
    for i in range(a) :
        for j in range(i,a):
            z = [0]
            z1 = z * 256
            ss = s[i:j+1]
            s1 = len(ss)
            b = 1
            for k in range(0,s1):
                asc = ord(ss[k])
                z1[asc]+=1
                if z1[asc] > 1 :
                    b*=0
                    break
            s1
            if b == 1 and s1 > lng:
                lng = s1
    return lng

# TODO: implement this function. You may delete this comment when you are done.
def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    a = len(s)
    lng = 0
    for i in range(a):
        z = [0] * 256
        b = 1
        for j in range(i,a):
            s1 = s[i:j+1]
            ls1 = len(s1)
            asc = ord(s[j])
            z[asc]+=1
            
            if z[asc] > 1 :
                b*=0
        
       
        if b == 1 and ls1 > lng :
            lng = ls1
      
    return lng


# TODO: implement this function. You may delete this comment when you are done.
def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    a = len(s)
    lng = 0
    for i in range(a):
        z = [0] * 256
        b = 1
        for j in range(i,a):
            ss = s[i:j+1]
            s1 = len(ss)
            asc = ord(s[j])
            z[asc]+=1
            if z[asc] > 1 :
                b*=0
                break
          
        if b == 1 and s1 > lng :
            lng = s1
            

    
    return lng
